version: '3'

services:
  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./api/app:/app/
      - ./data:/app/data
      - ./db:/app/db