FROM python:3.13-bookworm

ENV ROOT_DIR=/src

RUN mkdir "$ROOT_DIR"

COPY src $ROOT_DIR
COPY db /db
COPY data /data

COPY requirements.txt $ROOT_DIR
COPY entrypoint.sh $ROOT_DIR

WORKDIR $ROOT_DIR

RUN pip install -r $ROOT_DIR/requirements.txt

EXPOSE 8000