version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src/
      - ./data:/data
      - ./db:/db