version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src/
      - ./data:/data
      - ./db:/db
    command: granian --interface asgi --host 0.0.0.0 --port 8080 --workers 1 main:app