FROM prefecthq/prefect:2-latest

# Working directory
WORKDIR /app

# Put flow code into a separate volume (see volumes in compose)
COPY ../flows /app/flows

RUN pip install --no-cache-dir -r requirements-flows.txt

ENV PYTHONPATH="/app:/app/flows:${PYTHONPATH}"
